[shell]
  program = "/usr/bin/zsh"
  args = ["--login"]

[[hints.enabled]]
  regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|[^0-9a-zA-Z]go/|[^0-9a-zA-Z]b/|[^0-9a-zA-Z]cl/)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
  command = "open"
  post_processing = true
  mouse.enabled=true
  binding= { key="U", mods="Control|Shift" }

[window]
  opacity=1

[selection]
  save_to_clipboard = true

[mouse]
  bindings = [
    { mouse = "Right", mods = "None", action = "Paste" },
  ]

[debug]
  print_events = false
